//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityOrnek
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNotlar
    {
        public int Notid { get; set; }
        public Nullable<int> Ogrid { get; set; }
        public Nullable<int> Ders { get; set; }
        public Nullable<int> Sinav1 { get; set; }
        public Nullable<int> Sinav2 { get; set; }
        public Nullable<int> Sinav3 { get; set; }
        public Nullable<int> Ortalama { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual TblDersler TblDersler { get; set; }
        public virtual TblOgrenci TblOgrenci { get; set; }
    }
}
